### ISSUE TITLE
Only update fields in body on PUT requests

### ISSUE THREAD

**Issue by kmelve** [NDLANO/taxonomy-api#2]
Now `name` will be set to `null` if I PUT to for example `topics/{id}` with the following body 

```json
{
  "contentUri": "{id}"
}
```

Could we have the `name` persist as is if it's not added to the PUT-request body?

**Comment by sivhollup** [comment]
This is a design choice used in many projects, and we also follow this. Before doing PUT, you should perform a GET on the desired entity. Then change the fields that should be updated and PUT the entire entity. 

The main reason we do it this way is to make it easy to unset values. Otherwise we have no way to figure out whether the user wants to unset a value or deliberately set it to null.
